import type { Metadata } from 'next';
import { Instrument_Sans, JetBrains_Mono } from 'next/font/google';

import './globals.css';
import Header from '@/components/layout/Header';

const instrumentSans = Instrument_Sans({
  variable: '--font-instrument-sans',
  subsets: ['latin'],
});

const jetBrains = JetBrains_Mono({
  variable: '--font-jet-brains',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sr" className="dark">
      <body
        className={`${instrumentSans.variable} ${jetBrains.variable} font-sans antialiased bg-zinc-950 text-white min-h-screen flex flex-col`}
      >
        <Header />
        <main className="grow">{children}</main>
      </body>
    </html>
  );
}
